openapi: 3.0.0
info:
  title: Messages API
  version: 1.0.0
paths:
  /messages:
    get:
      summary: Get Messages
      description: Retrieves a list of messages.
      parameters:
        - name: status
          in: query
          description: Filter messages by status
          required: false
          schema:
            type: string
            enum:
              - sent
              - read
      responses:
        '200':
          description: Successful response, a list of messages is returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  messages:
                    type: array
                    items:
                      $ref: '#/components/schemas/Message'
              example:
                messages:
                  - text: "Hello, World!"
                    status: "read"
                    uuid: "1f099ef6-f198-64b8-8abc-1f4df5a3bc42"
                  - text: "How are you today?"
                    status: "sent"
                    uuid: "1f099ef6-f199-643a-b6a8-1f4df5a3bc42"
                  - text: "Thanks, I'm fine. How about you?"
                    status: "sent"
                    uuid: "1f099f1e-48e3-6318-a993-8f585faf4d6f"
        '404':
          description: Invalid status parameter
    post:
      summary: Send a Message
      description: Creates and dispatches a new message.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  description: The text you want to send
                  example: "This message for send"
              required:
                - text
      responses:
        '200':
          description: Message created successfully. Message uuid is returned.
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
                    format: uuid
              example:
                uuid: "1f099f35-e399-63dc-9b24-ff34b73edcb9"
components:
  schemas:
    Message:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
        text:
          type: string
        status:
          type: string
          enum:
            - sent
            - read
